name: Test release
on:
  workflow_dispatch:
    inputs:
      version:
        type: text
        description: 'Version number Eg: 4.2.0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Build
      - run: |
          npm ci
          npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lib_dist
          path: ./dist/
